---
- hosts: all
  become: true
  roles:
  - common

- hosts: prestashop
  become: true
  vars_files:
    - vars/main.yml
  roles:
  - prestashop
  
- hosts: shop
  become: true
  vars_files:
    - vars/main.yml
  roles:
  - shop
  
